### ISSUE TITLE
Getting "Illegal instruction: 4"

### ISSUE THREAD

**Issue by jjsoliveira** [nylander/MrModeltest2#1]
Hi

I have installed Mrmodeltest2 according instructions and I have generated a test.scores file using paup. But when I try to run mrmodeltest2 (any one of the bin), it does not work for illegal instruction:4. I think that it is due to my Mac OX version 10.7.5. Is there a readable bin for my machine?

Thanks

**Comment by nylander** [comment]
Hi,
unfortunately, I don't have a Macintosh computer. This is why precompiled binaries (http://www.abc.se/~nylander/mrmodeltest2/bin.zip) might be too old/new for your specific version. I will try to add an appropriate binary when I can get my hands on a Mac with a compiler. Meanwhile you might want to try to download the source and compile it on your local machine.
/Johan

**Comment by jjsoliveira** [comment]
Hi Johan,

I got it! Sorry, I am new in Mac and doing compilations. I did't not perceive that I have already compiled and  I have already the proper binary. Sorry again!

Thanks a lot!

Jadson
